apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-pvc
  namespace: prod
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi