apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: prod
  labels: { app: db }
spec:
  replicas: 1
  selector: { matchLabels: { app: db } }
  template:
    metadata: { labels: { app: db } }
    spec:
      containers:
        - name: mysql
          image: ofcan1010/db:v1
          ports: [{ containerPort: 3306 }]
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: mysql-pvc }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: prod
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests: { storage: 5Gi }